export type Language = "en" | "hi";

const HINDI: Record<string, string> = {
  "Home": "होम", "About": "हमारे बारे में", "How It Works": "यह कैसे काम करता है", "Resources": "संसाधन", "Support": "सहायता", "Contact": "संपर्क", "Privacy": "गोपनीयता",
  "Login": "लॉगिन", "Register": "रजिस्टर", "Create account": "खाता बनाएं", "Forgot password?": "पासवर्ड भूल गए?", "Reset password": "पासवर्ड रीसेट करें", "Verify email": "ईमेल सत्यापित करें",
  "Dashboard": "डैशबोर्ड", "Daily Journal": "दैनिक जर्नल", "Voice Journal": "वॉइस जर्नल", "AI Companion": "AI साथी", "History": "इतिहास", "Profile": "प्रोफ़ाइल", "Settings": "सेटिंग्स", "Help": "मदद",
  "Toggle theme": "थीम बदलें", "Switch to Hindi": "हिंदी पर स्विच करें", "Switch to English": "अंग्रेज़ी पर स्विच करें",
  "Admin": "प्रशासन", "Admin Console": "एडमिन कंसोल", "Personnel": "कर्मचारी", "Risk Monitoring": "जोखिम निगरानी", "Alerts": "अलर्ट", "Analytics": "विश्लेषण", "Audit Logs": "ऑडिट लॉग", "System Settings": "सिस्टम सेटिंग्स",
  "Sign out": "साइन आउट", "Need help?": "मदद चाहिए?", "Get Started": "शुरू करें", "Learn more": "और जानें", "Read more": "और पढ़ें", "Save": "सहेजें", "Submit": "जमा करें", "Cancel": "रद्द करें", "Close": "बंद करें", "Back": "वापस", "Next": "आगे", "Continue": "जारी रखें", "Retry": "पुनः प्रयास करें", "Delete": "हटाएं", "Edit": "संपादित करें", "Update": "अपडेट करें", "Search": "खोजें", "Filter": "फ़िल्टर", "Clear": "साफ़ करें", "Loading": "लोड हो रहा है…",
  "Good morning": "सुप्रभात", "Good afternoon": "नमस्कार", "Good evening": "शुभ संध्या", "Today": "आज", "Yesterday": "कल", "just now": "अभी", "No results found": "कोई परिणाम नहीं मिला", "No data available": "कोई डेटा उपलब्ध नहीं है",
  "Check-in": "चेक-इन", "Daily Check-ins": "दैनिक चेक-इन", "Mood": "मूड", "Mood trend": "मूड ट्रेंड", "Journal": "जर्नल", "Voice": "वॉइस", "Wellbeing": "वेलबीइंग", "Wellbeing pulse": "वेलबीइंग पल्स", "Stable": "स्थिर", "Normal": "सामान्य", "Low": "कम", "Moderate": "मध्यम", "Elevated": "बढ़ा हुआ", "High": "उच्च", "Critical": "गंभीर",
  "Great": "बहुत अच्छा", "Good": "अच्छा", "Okay": "ठीक", "Rough": "मुश्किल", "Write a short reflection first.": "पहले एक छोटा अनुभव लिखें।", "Please try again.": "कृपया फिर से प्रयास करें।", "Couldn't load dashboard": "डैशबोर्ड लोड नहीं हो सका", "Couldn't load journals.": "जर्नल लोड नहीं हो सके।", "Failed to save entry.": "प्रविष्टि सहेजी नहीं जा सकी।", "Entry deleted.": "प्रविष्टि हटा दी गई।", "Draft saved.": "ड्राफ्ट सहेजा गया।", "Entry recorded": "प्रविष्टि दर्ज की गई",
  "Encrypted in transit": "स्थानांतरण के दौरान एन्क्रिप्टेड", "Accessible only to authorised personnel": "केवल अधिकृत कर्मियों के लिए उपलब्ध", "Encrypted at rest": "संग्रहित डेटा एन्क्रिप्टेड", "Consent-tracked": "सहमति दर्ज", "Audit-logged": "ऑडिट लॉग दर्ज",
  "Open menu": "मेनू खोलें", "Go back": "वापस जाएं", "Search personnel": "कर्मचारी खोजें", "Search by name, service number, or email…": "नाम, सेवा क्रमांक या ईमेल से खोजें…", "All units": "सभी यूनिट", "All levels": "सभी स्तर", "Filter by unit": "यूनिट के अनुसार फ़िल्टर करें", "Filter by wellbeing level": "वेलबीइंग स्तर के अनुसार फ़िल्टर करें", "Wellbeing Indicator": "वेलबीइंग संकेतक", "Last Check-in": "अंतिम चेक-इन", "Last Activity": "अंतिम गतिविधि", "View": "देखें", "View profile": "प्रोफ़ाइल देखें", "Directory": "निर्देशिका", "Search and review operational records. Sensitive clinical content is restricted to authorized roles.": "परिचालन रिकॉर्ड खोजें और देखें। संवेदनशील नैदानिक सामग्री अधिकृत भूमिकाओं तक सीमित है।", "No personnel found": "कोई कर्मचारी नहीं मिला", "Try adjusting your search or filters.": "अपनी खोज या फ़िल्टर बदलकर देखें।", "Showing": "दिखाया जा रहा है", "of": "में से", "Page": "पृष्ठ", "Prev": "पिछला", "Unknown": "अज्ञात", "Unassigned": "निर्धारित नहीं", "active": "सक्रिय", "locked": "लॉक", "suspended": "निलंबित", "pending verification": "सत्यापन लंबित",
  "Password": "पासवर्ड", "Email": "ईमेल", "Name": "नाम", "Phone": "फ़ोन", "Role": "भूमिका", "Status": "स्थिति", "Date": "तारीख", "Actions": "कार्रवाइयां", "Active": "सक्रिय", "Inactive": "निष्क्रिय", "Pending": "लंबित", "Completed": "पूर्ण",
  "View assessment history & results": "आकलन इतिहास और परिणाम देखें", "View journal entries (sensitive)": "जर्नल प्रविष्टियां देखें (संवेदनशील)", "View AI conversations (sensitive)": "AI बातचीत देखें (संवेदनशील)", "View wellbeing indicators": "वेलबीइंग संकेतक देखें", "Manage user accounts": "उपयोगकर्ता खाते प्रबंधित करें", "Manage system settings": "सिस्टम सेटिंग्स प्रबंधित करें",
  "Stress": "तनाव", "Burnout": "बर्नआउट", "Sleep": "नींद", "Relationships": "रिश्ते", "Family Separation": "परिवार से दूरी", "Operational Stress": "परिचालन तनाव", "Relaxation": "विश्राम", "Breathing Exercises": "श्वास अभ्यास", "Mental Wellbeing": "मानसिक वेलबीइंग", "Professional Support": "पेशेवर सहायता",
  "Personnel profile": "कर्मचारी प्रोफ़ाइल", "View personnel profile": "कर्मचारी प्रोफ़ाइल देखें", "Manage alerts": "अलर्ट प्रबंधित करें", "Manage users": "उपयोगकर्ता प्रबंधित करें", "View analytics": "विश्लेषण देखें", "View audit logs": "ऑडिट लॉग देखें", "Administrator": "प्रशासक", "Supervisor": "पर्यवेक्षक", "Mental Health Professional": "मानसिक स्वास्थ्य विशेषज्ञ", "Super Administrator": "मुख्य प्रशासक",
  "Accessibility": "अभिगम्यता", "Accessibility options": "अभिगम्यता विकल्प", "Font size": "फ़ॉन्ट आकार", "High contrast": "उच्च कंट्रास्ट", "Reduce motion": "गतिशीलता कम करें", "Reset": "रीसेट", "Menu": "मेनू", "Toggle script": "भाषा बदलें", "Need immediate help?": "तुरंत मदद चाहिए?",
  "Show password": "पासवर्ड दिखाएं", "Hide password": "पासवर्ड छिपाएं", "Too short": "बहुत छोटा", "Weak": "कमज़ोर", "Fair": "ठीक", "Strong": "मज़बूत",
  "Create your account": "अपना खाता बनाएं", "Join CRPF MHS": "CRPF MHS से जुड़ें", "Sign in": "साइन इन", "Already have an account?": "क्या आपका पहले से खाता है?", "Full name": "पूरा नाम", "Service no.": "सेवा क्रमांक", "Rank": "पद", "Unit": "यूनिट", "optional": "वैकल्पिक", "At least 8 characters": "कम से कम 8 अक्षर", "Password strength indicator": "पासवर्ड की मज़बूती का संकेतक", "What you're signing up for": "आप जिस सेवा के लिए पंजीकरण कर रहे हैं", "Platform": "प्लेटफॉर्म", "Account": "खाता", "English": "अंग्रेज़ी", "Hindi": "हिंदी", "Privacy policy": "गोपनीयता नीति", "Forgot your password?": "पासवर्ड भूल गए?", "Remember me": "मुझे याद रखें", "Welcome back": "वापसी पर स्वागत है", "Log in to your account": "अपने खाते में लॉगिन करें", "Don't have an account?": "क्या आपका खाता नहीं है?",
  "Calm support for the moments that matter.": "महत्वपूर्ण पलों के लिए शांत सहायता।", "Wellbeing, early support, and confidential check-ins for armed forces personnel.": "सशस्त्र बलों के कर्मियों के लिए वेलबीइंग, प्रारंभिक सहायता और गोपनीय चेक-इन।", "Private daily check-ins, journaling, an AI-assisted companion for in-between moments, and discreet human support when you need it.": "निजी दैनिक चेक-इन, जर्नलिंग, बीच के पलों के लिए AI-सहायता प्राप्त साथी और जरूरत पड़ने पर गोपनीय मानवीय सहायता।",
  "Wellbeing, early support, and confidential check-ins for armed forces personnel. Private daily check-ins, journaling, an AI-assisted companion for in-between moments, and discreet human support when you need it.": "सशस्त्र बलों के कर्मियों के लिए वेलबीइंग, प्रारंभिक सहायता और गोपनीय चेक-इन। निजी दैनिक चेक-इन, जर्नलिंग, बीच के पलों के लिए AI-सहायता प्राप्त साथी और जरूरत पड़ने पर गोपनीय मानवीय सहायता।",
  "Your wellbeing matters": "आपका वेलबीइंग महत्वपूर्ण है", "Submit assessment": "आकलन जमा करें", "Start assessment": "आकलन शुरू करें", "Assessment": "आकलन", "Assessment history": "आकलन इतिहास", "Recent activity": "हाल की गतिविधि", "Quick actions": "त्वरित कार्रवाइयां", "Write a reflection": "अपना अनुभव लिखें", "Save draft": "ड्राफ्ट सहेजें", "Record entry": "प्रविष्टि दर्ज करें", "No journal entries yet": "अभी तक कोई जर्नल प्रविष्टि नहीं है", "Conversation": "बातचीत", "Send message": "संदेश भेजें", "Type your message": "अपना संदेश लिखें", "Start a conversation": "बातचीत शुरू करें", "No conversations yet": "अभी तक कोई बातचीत नहीं है", "View details": "विवरण देखें", "View all": "सभी देखें", "Overview": "अवलोकन", "Total personnel": "कुल कर्मचारी", "Open alerts": "खुले अलर्ट", "Average wellbeing": "औसत वेलबीइंग", "Recent alerts": "हाल के अलर्ट", "No alerts": "कोई अलर्ट नहीं",
  "A confidential space to monitor, reflect on, and support your mental wellbeing.": "आपके मानसिक वेलबीइंग पर नज़र रखने, विचार करने और सहायता पाने के लिए एक गोपनीय स्थान।", "What you're signing up for: self-guided check-ins, AI-assisted reflection, and confidential support pathways.": "आप जिस सेवा के लिए पंजीकरण कर रहे हैं: स्व-निर्देशित चेक-इन, AI-सहायता प्राप्त चिंतन और गोपनीय सहायता मार्ग।", "By creating an account, you consent to CRPF MHS processing your wellbeing data to provide personalised support.": "खाता बनाकर, आप व्यक्तिगत सहायता प्रदान करने के लिए CRPF MHS को अपने वेलबीइंग डेटा को संसाधित करने की सहमति देते हैं।",
  "New entry": "नई प्रविष्टि", "Speak to type": "बोलकर लिखें", "Read aloud": "जोर से पढ़ें", "Save Draft": "ड्राफ्ट सहेजें", "Submit Entry": "प्रविष्टि जमा करें", "Your entries": "आपकी प्रविष्टियां", "Refresh": "रिफ्रेश करें", "What would you like to reflect on today?": "आज आप किस बारे में विचार करना चाहेंगे?",
  "How are you feeling today?": "आज आप कैसा महसूस कर रहे हैं?", "Complete your welcome check-in": "अपना स्वागत चेक-इन पूरा करें", "Start check-in": "चेक-इन शुरू करें", "New chat": "नई बातचीत", "Chats": "बातचीतें",
};

const ENGLISH = Object.fromEntries(Object.entries(HINDI).map(([english, hindi]) => [hindi, english]));

export function translate(value: string, language: Language): string {
  if (language === "en") return ENGLISH[value] ?? value;
  return HINDI[value] ?? value;
}

export function translationPair(value: string): { en: string; hi: string } {
  return { en: ENGLISH[value] ?? value, hi: HINDI[value] ?? value };
}
