"""add_hrms_biometrics_and_interventions

Revision ID: 6f8368c3e935
Revises: c8177f6d436d
Create Date: 2026-09-20 18:48:29.379030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f8368c3e935'
down_revision: Union[str, None] = 'c8177f6d436d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometric_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('personnel_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resting_heart_rate', sa.Float(), nullable=True),
    sa.Column('heart_rate_variability', sa.Float(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality_score', sa.Float(), nullable=True),
    sa.Column('deep_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('stress_index', sa.Float(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('device_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_readings_personnel_id'), 'biometric_readings', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_biometric_readings_timestamp'), 'biometric_readings', ['timestamp'], unique=False)
    op.create_table('deployment_histories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('personnel_id', sa.String(length=36), nullable=False),
    sa.Column('deployment_name', sa.String(length=100), nullable=False),
    sa.Column('terrain_type', sa.String(length=50), nullable=False),
    sa.Column('hard_posting', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_months', sa.Float(), nullable=True),
    sa.Column('family_separation_months', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_histories_personnel_id'), 'deployment_histories', ['personnel_id'], unique=False)
    op.create_table('duty_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('personnel_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift_type', sa.String(length=50), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('consecutive_days_on_duty', sa.Integer(), nullable=False),
    sa.Column('is_overtime', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_schedules_personnel_id'), 'duty_schedules', ['personnel_id'], unique=False)
    op.create_table('leave_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('personnel_id', sa.String(length=36), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('applied_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('days_since_last_leave', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_records_personnel_id'), 'leave_records', ['personnel_id'], unique=False)
    op.create_table('transfer_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('personnel_id', sa.String(length=36), nullable=False),
    sa.Column('from_unit', sa.String(length=100), nullable=False),
    sa.Column('to_unit', sa.String(length=100), nullable=False),
    sa.Column('transfer_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transfer_count_last_3_years', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_records_personnel_id'), 'transfer_records', ['personnel_id'], unique=False)
    op.create_table('welfare_interventions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('personnel_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_plan', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recommended_by_xai', sa.Boolean(), nullable=False),
    sa.Column('contributing_factors', sa.Text(), nullable=True),
    sa.Column('assigned_officer_id', sa.String(length=36), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_welfare_interventions_alert_id'), 'welfare_interventions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_welfare_interventions_personnel_id'), 'welfare_interventions', ['personnel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_welfare_interventions_personnel_id'), table_name='welfare_interventions')
    op.drop_index(op.f('ix_welfare_interventions_alert_id'), table_name='welfare_interventions')
    op.drop_table('welfare_interventions')
    op.drop_index(op.f('ix_transfer_records_personnel_id'), table_name='transfer_records')
    op.drop_table('transfer_records')
    op.drop_index(op.f('ix_leave_records_personnel_id'), table_name='leave_records')
    op.drop_table('leave_records')
    op.drop_index(op.f('ix_duty_schedules_personnel_id'), table_name='duty_schedules')
    op.drop_table('duty_schedules')
    op.drop_index(op.f('ix_deployment_histories_personnel_id'), table_name='deployment_histories')
    op.drop_table('deployment_histories')
    op.drop_index(op.f('ix_biometric_readings_timestamp'), table_name='biometric_readings')
    op.drop_index(op.f('ix_biometric_readings_personnel_id'), table_name='biometric_readings')
    op.drop_table('biometric_readings')
    # ### end Alembic commands ###
